
services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    container_name: nest-app-dev
    ports:
      - "3000:3000"
    env_file: ".env"
    networks:
      - clinic-manager-network
  db:
    container_name: clinic-manager-db
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  #  ports:
  #    - "5432:5432"
  # Quite la exposición del puerto 5432 para que la base de datos no se pueda acceder desde el exterior
    networks:
      - clinic-manager-network

volumes:
  postgres_data:

networks:
  clinic-manager-network:
    driver: bridge