version: '3.8'

services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    command: node dist/main.js
    container_name: nest-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  
